24 creazione header
AkasakaRyuunoske/tempest-double pull request #30
Opened 2024-11-14 10:32 UTC by cay3na

2024-11-21 12:24 UTC, AkasakaRyuunoske requested changes
Tutto ok fin a questo punto. Manca responsivness del header.

2024-11-21 14:00 UTC, cay3na commented
> Tutto ok fin a questo punto. Manca responsivness del header.

e gia responsive, altre cose che vuoi cambiare?

2024-11-21 15:41 UTC, AkasakaRyuunoske requested changes
Un piccolo fix e mergio

2024-11-21 15:41 UTC, AkasakaRyuunoske commented on src/main/resources/templates/AssetsPage/header.html
> +            <a href="/home">Home</a>
mettere link a altre pagine nel href,

/assets
/simulation
/history

2024-11-22 13:28 UTC, AkasakaRyuunoske approved these changes
Ottimo lavoro. Mergio

2024-11-23 08:24 UTC, merged